[package]
name = "aw-soc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile-register = "0.2.1"
base-address = "0.0.0"
embedded-hal = "1.0.0-alpha.9"
embedded-hal-nb = "1.0.0-alpha.1"
nb = "1"
uart16550 = "0.0.0"

[dev-dependencies]
memoffset = "0.8"

[features]
# D1-like chips: D1-H, D1s, F133.
d1 = []
